Add unit test coverage to nhsuk-header-search
nhsuk/nhsuk-header-search pull request #6
Opened 2023-02-16 15:46 UTC by roshaanbajwa

2023-02-17 09:29 UTC, the-nathan-smith approved these changes

2023-02-20 09:34 UTC, will-dyson-nhsd requested changes

2023-02-28 10:56 UTC, the-nathan-smith approved these changes

2023-02-28 11:09 UTC, will-dyson-nhsd approved these changes

2023-02-28 11:10 UTC, will-dyson-nhsd commented on src/js/header-search.js
> -export default () => {
Reduced changes are acceptable and needed for tests

2023-02-28 11:13 UTC, merged